name: CI - Desarrollo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint
        run: npm run lint

      - name: Ejecutar pruebas unitarias
        run: npm test

      - name: Ejecutar API Tests con Newman
        run: npm run api-test

