name: CI - Desarrollo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESLint
        run: npm run lint

      - name: Ejecutar pruebas unitarias
        run: npm test

      - name: Ejecutar API Tests con servidor
        run: npm run start:test

      - name: Iniciar servidor Express en segundo plano
        run: node src/app.js &

      - name: Esperar a que el servidor esté listo
        run: npx wait-on http://localhost:3000

      - name: Ejecutar pruebas de interfaz con Cypress
        run: npm run cypress:run
      

